services:
  msa:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: msA
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_HIKARI_SCHEMA: santa_fe
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.20.68.92:5432/santa_fe_db?ApplicationName=MsA
      SPRING_DATASOURCE_USERNAME: santa_fe_admin
      SPRING_DATASOURCE_PASSWORD: santa_fe
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    network_mode: "host"